config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :stores do
    member do
      put :sort  #stores/sort
    end
  end

  resources :groups do
    member do
      # post :join
      post :quit
      get :manager
      patch :transfer  #groups/1234567/manager
    end
    resource :invite_link, only: [ :show ]
  end
  
  resources :invites, param: :invite_token, only: [ :new ] do
    resources :memberships, only: [ :new, :create ]
  end
  
  resources :events do
  end
  
  resources :trays do
  end
  #trays/1234567/create

  # Defines the root path route ("/")
  root "home#index"
end

app/models/store.rb
class Store < ApplicationRecord
  acts_as_paranoid

  extend FriendlyId
  friendly_id :code_generator, use: :slugged
  
  belongs_to :user
  has_many :meals
  has_many :events
  accepts_nested_attributes_for :meals, reject_if: :all_blank, allow_destroy: true
  has_one_attached :menu

  validates :name, :county, :district, :tel, presence: true
  validates :slug, uniqueness: true

  scope :available, -> { where(online: true)}
  scope :disable, -> { where(online: false)}
  default_scope { order('updated_at DESC') }

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end
  
  private
  def code_generator
    "#{name} - #{SecureRandom.hex[0,8]}"
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!
  before_action :find_store, only: [:show, :edit, :update, :destroy, :sort]

  def index
    # @stores = current_user.stores.includes(:meals).order(created_at: :desc)
    @pagy, @stores = pagy(current_user.stores.includes(:meals).order(created_at: :desc))
  end
  
  def new
    @store = current_user.stores.new
    @store.meals.build
  end
  
  def create
    @store = current_user.stores.new(store_params)
    
    if @store.save
      redirect_to stores_path, notice: '新增店家成功！'
    else
      render :new, status: :unprocessable_entity, content_type: "text/html"
      headers["Content-Type"] = "text/html"
    end
  end
  
  def edit
    
  end

  def show
    
  end

  def update
    if @store.update!(store_params)
      redirect_to edit_store_path, notice: '資料更新成功！'
    else
      render :edit, status: :unprocessable_entity, content_type: "text/html"
      headers["Content-Type"] = "text/html"
    end
  end
  
  def destroy
    @store.destroy
    redirect_to stores_path, notice: '店家已刪除！'
  end

  def sort
    find_meal
    @meal.insert_at(params[:to].to_i + 1)
    render json: {status: 'ok'}
  end
  
  private
  
  def find_store
    @store = current_user.stores.friendly.find(params[:id])
  end
  
  def find_meal
    @meal = @store.meals.find(params[:meal_id])
  end

  def store_params
    params.require(:store).permit(:name, :branch, :county, :district, :street_address, :tel, :note, :online, :menu,
                                  meals_attributes: [ :id, :name, :price, :description, :_destroy]
                                  )
  end
end

app/views/stores/_meal_card.html.erb
<div class="card">
  <div class="card-header d-flex">
    <div class="">
      <span class="fs-4">
        <!-- <%= store.name %> -->
        餐點
      </span> 
    </div>
    <div class="ms-auto">
      <%= link_to "編輯餐點", edit_store_meal_path ,class: 'btn btn-primary text-light' %>
      <%= link_to "新增餐點", new_store_meal_path ,class: 'btn btn-primary text-light' %>
    </div>
  </div>
  <div class="card-body">
    <!-- <h5 class="card-title">Special title treatment</h5> -->
    <p class="card-text">
      地址：<%= store.city + store.district + store.street_address %>
    </p>
    <p>
      電話：<%= store.tel %>
    </p>
    <p>
      備註：<%= store.note %>
    </p>
  </div>
</div>

app/views/stores/_meal_fields.html.erb
<div class="row nested-fields" data-new-record="<%= form.object.new_record? %>">
  <div class="col-4 mb-2">
    <%= form.text_field :name, class: 'form-control', placeholder: '餐點名稱', hide_label: true %>
  </div>
  <div class="col-2 mb-2">
    <%= form.number_field :price, class: 'form-control', placeholder: '價格', hide_label: true %>
  </div>
  <div class="col-5 mb-2">
    <%= form.text_field :description, class: 'form-control', placeholder: '描述', hide_label: true %>
  </div>
  <div class="col-1 mb-2 align-items-center d-flex">
    <%= link_to '#', data: {action: 'meal-fields#remove_meal'} do %>
      <i class="bi bi-trash fs-5"></i>
    <% end %>
  </div>
  <%= form.hidden_field :_destroy %>
</div>

app/views/stores/_meal_show_card.html.erb
<div class="card mb-3">
  <div class="card-header d-flex">
    <div>
      <span class="fs-4">
        <%= store.name %>
      </span> 
      <span>的菜單</span>
    </div>
  </div>
  <div class="card-body">
    <div class="px-4 py-2">
      <div class="row p-1 border-bottom border-2 border-primary">
        <div class="col-1">
          
        </div>
        <div class="col-4">
          餐點名稱
        </div>
        <div class="col-2">
          價格
        </div>
        <div class="col-5">
          描述
        </div>
      </div>
      <div class="sortable-items">
        <% store.meals.each do |meal| %>
          <div class="row py-2 border-bottom item" data-item="<%= dom_id(meal) %>">
            <div class="col-1">
              <i class="fa-solid fa-grip-vertical"></i>
            </div>
            <div class="col-4">
              <%= meal.name %>
            </div>
            <div class="col-2">
              <%= meal.price %>
            </div>
            <div class="col-5">
              <%= meal.description %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card-footer text-muted fw-light">
    <span>小提示：可使用拖拉調整餐點順序</span>
  </div>
</div>

  

app/views/stores/_store_form.html.erb
<%= bootstrap_form_with model: store, data: "turbo: false" do |form| %>
  <div class="card">
    <div class="card-header d-flex">
      <div id="">
        <span class="fs-3">編輯店家</span>
      </div>
    </div>
    <div class="row card-body">
      <div class="col-md-3 col-sm-6 mb-2">
        <%= form.text_field :name, class: 'form-control', label: '店名' %>
      </div>
      <div class="col-md-3 col-sm-6 mb-2">
        <%= form.text_field :branch, class: 'form-control', label: '分店名稱' %>
      </div>
      <div class="col-md-6 col-sm-12 mb-2">
        <%= form.text_field :tel, class: 'form-control', label: '電話' %>
      </div>
      <div class="city-selector col-md-6 col-sm-12 mb-2">
        <div class="blo me-2">
          <%= form.label :county, '縣市', class: 'form-label' %>
          <select class="county" data-value="<%= store.county %>"></select>
        </div>
        <div class="blo">
          <%= form.label :district, '鄉鎮市區', class: 'form-label' %>
          <select class="district" data-value="<%= store.district %>"></select>
        </div>
      </div>
      <div class="col-md-6 col-sm-12 mb-2">
        <%= form.text_field :street_address, class: 'form-control', label: '街道名稱' %>
      </div>
      <div class="col-12 mb-2">
        <%= form.text_area :note, class: 'form-control', rows: 3, label: '備註' %>
      </div>
      <div class="col-md-3 col-sm-12 mb-2">
        <%= form.check_box :online, class: 'form-check-input' , label: '營業中' %>
      </div>
      <div class="col-12 mb-2">
        <%= form.file_field :menu, class: 'form-control', label: '上傳菜單' %>
      </div>
      
      <!-- <div>
        <%= form.label :opening, '營業時間', class: 'form-label' %>
      </div>
      <div class="col-4 input-group">
        <%= form.text_field :opening, class: 'form-control' %>
        <span class="input-group-text">-</span>
        <%= form.text_field :opening, class: 'form-control' %>
      </div> -->
    </div>
  </div>
  
  <div class="card mt-4">
    <div class="card-header d-flex">
      <div id="">
        <span class="fs-3">編輯餐點</span>
      </div>
    </div>
    <div class="card-body" data-controller="meal-fields">

      <template data-meal-fields-target="template">
        <%= form.fields_for :meals, Meal.new, child_index: 'NEW_RECORD' do |meal| %>
          <%= render 'meal_fields', form: meal %>
        <% end %>
      </template>

      <%= form.fields_for :meals do |meal_form| %>
        <%= render 'meal_fields', form: meal_form %>
      <% end %>
      <div data-meal-fields-target="addBtn">
        <%= link_to "新增餐點", '#', class: 'btn btn-success', data: {action: 'meal-fields#add_meal'} %>
      </div>
    </div>
  </div>
    
    
  <div class="my-2 d-flex justify-content-around">
    <%= form.submit "更新", class: 'btn btn-primary text-light' %>
    <%= link_to "取消編輯" , store_path(store), class: 'btn btn-primary text-light' %>
  </div>
<% end %>

app/views/stores/_store_list.html.erb
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3">
  <% stores.each do |store| %>
    <div class="col">
      <div class="card my-2">
        <!-- <img src="..." class="card-img-top" alt="..."> -->
        <div class="card-body">
          <div class="d-flex">
            <h5 class="card-title mb-0">
              <%= store.name %>
              <span class="fs-6">
                <%= store.branch %>
              </span>
            </h5>
          </div>
          <div class="card-text mt-2">
            <div>
              電話：<%= store.tel %>
            </div>
            <div>
              地址：<%= store.county + store.district + store.street_address %>
            </div>
            <div>
              備註：<%= store.note %>
            </div>
          </div>
        </div>
        <ul class="list-group list-group-flush">
          <% store.meals.each.with_index do |meal, index| %>
            <% if index < 3 %>
              <li class="list-group-item d-flex justify-content-between">
                <span><%= meal.name %></span>
                <span>$<%= meal.price %></span>
              </li>
            <% end %>
          <% end %>
        </ul>
        <div class="card-body d-flex">
          <%= link_to "查看與編輯", store_path(store) %>
          <%= link_to "刪除", store_path(store), class: 'ms-auto text-danger', data: { turbo_method: :delete, turbo: true, turbo_confirm: '確認是否刪除？'} %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/stores/_store_new.html.erb
<%= bootstrap_form_with model: store, data: "turbo: false" do |form| %>
  <div class="card">
    <div class="card-header d-flex">
      <div>
        <span class="fs-3">新增店家</span>
      </div>
    </div>
    <div class="row card-body">
      <div class="col-md-3 col-sm-6 mb-2">
        <%= form.text_field :name, class: 'form-control', label: '店名', required: true %>
      </div>
      <div class="col-md-3 col-sm-6 mb-2">
        <%= form.text_field :branch, class: 'form-control', label: '分店名稱' %>
      </div>
      <div class="col-md-6 col-sm-12 mb-2">
        <%= form.text_field :tel, class: 'form-control', label: '電話', required: true %>
      </div>
      <div class="city-selector col-md-6 col-sm-12 mb-2">
        <div class="blo me-2">
          <%= form.label :county, '縣市', class: 'form-label' %>
          <select class="county" data-value="<%= store.county %>" required="true"></select>
        </div>
        <div class="blo">
          <%= form.label :district, '鄉鎮市區', class: 'form-label' %>
          <select class="district" data-value="<%= store.district %>" required="true"></select>
        </div>
      </div>
      <div class="col-md-6 col-sm-12 mb-2">
        <%= form.text_field :street_address, class: 'form-control', label: '街道名稱' %>
      </div>
      <div class="col-12 mb-2">
        <%= form.text_area :note, class: 'form-control', rows: 3, label: '備註' %>
      </div>
      <div class="col-md-3 col-sm-12">
        <%= form.check_box :online, class: 'form-check-input', label: '營業中' %>
        <!-- <%= form.label :online, '營業中', class: 'form-check-label' %> -->
      </div>
      <!-- <div>
        <%= form.label :opening, '營業時間', class: 'form-label' %>
      </div>
      <div class="col-4 input-group">
        <%= form.text_field :opening, class: 'form-control' %>
        <span class="input-group-text">-</span>
        <%= form.text_field :opening, class: 'form-control' %>
      </div> -->
    </div>
  </div>
    
  <div class="mt-2">
    <%= form.submit class: 'btn btn-primary text-light' %>
  </div>
<% end %>

app/views/stores/_store_show_card.html.erb
<div class="card mb-3">
  <div class="card-header d-flex">
    <div class="">
      <span class="fs-4">
        <%= store.name %>
      </span> 
      <span class="fs-6">
        <%= store.branch %>
        <% if store.branch? %>
          分店
        <% end %>
      </span> 
    </div>
  </div>
  <div class="card-body">
    <p class="card-text">
      地址：<%= store.county + store.district + store.street_address %>
    </p>
    <p>
      電話：<%= store.tel %>
    </p>
    <p>
      備註：<%= store.note %>
    </p>
  </div>
</div>

app/views/stores/edit.html.erb
<div>
  <%= render 'store_form', store: @store %>
  
  <% if @store.menu.attached? %>
    <div class="card mb-3">
      <div class="card-header d-flex">
        <div>
          <span class="fs-4">
            <%= @store.name %>
          </span> 
          <span>的菜單圖片</span>
        </div>
        <div class="ms-auto">
        </div>
      </div>
      <div class="card-body">
        <div class="d-flex justify-content-center">
          <%= image_tag @store.menu.variant(resize: '800x800') if @store.menu.attached? %>
        </div>
      </div>
    </div>
  <% end %>

</div>
  

app/views/stores/index.html.erb
<div class="d-flex justify-content-between align-items-start">
  <h2>我的店家清單</h2>
  <%= link_to "新增店家" , new_store_path, class: 'btn btn-success mb-2' %>
</div>

<!-- Nav tabs -->
<ul class="nav nav-tabs" id="storeTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="online-tab" data-bs-toggle="tab" data-bs-target="#online" type="button" role="tab" aria-controls="online" aria-selected="true">營業中</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="offline-tab" data-bs-toggle="tab" data-bs-target="#offline" type="button" role="tab" aria-controls="offline" aria-selected="false">停業中</button>
  </li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="online" role="tabpanel" aria-labelledby="online-tab" tabindex="0">
    <%= render 'store_list', stores: @stores.available %>
  </div>
  <div class="tab-pane" id="offline" role="tabpanel" aria-labelledby="offline-tab" tabindex="0">
    <%= render 'store_list', stores: @stores.disable %>
  </div>
</div>

<div class="pagination justify-content-center mt-2">
  <%== pagy_bootstrap_nav(@pagy).html_safe %>
</div>

app/views/stores/new.html.erb
<%= render 'store_new', store: @store %>

app/views/stores/show.html.erb
<%= render 'store_show_card', store: @store %>
<%= render 'meal_show_card' , store: @store %>
<div class="d-flex justify-content-center mb-3">
  <%= link_to "編輯店家及餐點" , edit_store_path(@store), class: 'btn btn-primary text-light' %>
</div>

<% if @store.menu.attached? %>
  <div class="card mb-3">
    <div class="card-header d-flex">
      <div>
        <span class="fs-4">
          <%= @store.name %>
        </span>
        <span>的菜單圖片</span>
      </div>
      <div class="ms-auto">
      </div>
    </div>
    <div class="card-body">
      <div class="d-flex justify-content-center">
        <%= image_tag @store.menu.variant(resize: '800x800' ), class: 'img-fluid' if @store.menu.attached? %>
      </div>
    </div>
  </div>
<% end %>