config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :stores do
    member do
      put :sort  #stores/sort
    end
  end

  resources :groups do
    member do
      # post :join
      post :quit
      get :manager
      patch :transfer  #groups/1234567/manager
    end
    resource :invite_link, only: [ :show ]
  end
  
  resources :invites, param: :invite_token, only: [ :new ] do
    resources :memberships, only: [ :new, :create ]
  end
  
  resources :events do
  end
  
  resources :trays do
  end
  #trays/1234567/create

  # Defines the root path route ("/")
  root "home#index"
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: :user_id
  has_one :token, class_name: "Invite", dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user
  has_many :events
  validates :name, presence: true

  extend FriendlyId
  friendly_id :code_generator, use: :slugged

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end

  def editable?(user)
    user && user == owner
  end

  private
  def code_generator
    "#{name} - #{SecureRandom.hex[0,8]}"
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_group_self, only: [:edit, :update, :destroy, :manager, :transfer]
  before_action :find_group, only: [:show, :quit]

  def index
    @groups = current_user.participated_groups.order(updated_at: :desc)
    # @groups = Group.order(updated_at: :desc)
  end

  def new
    @group = current_user.groups.new
  end

  def create
    @group = current_user.groups.new(group_params)
    
    if @group.save
      Invite.where(group: @group).create
      current_user.join!(@group)
      redirect_to groups_path, notice: "團體新增成功！"
    else
      render :new, status: :unprocessable_entity, content_type: "text/html"
      headers["Content-Type"] = "text/html"
    end
  end
  
  def edit
    
  end
  
  def update
    if @group.update(group_params)
      redirect_to groups_path, notice: "團體更新成功！"
    else
      render :edit, status: :unprocessable_entity, content_type: "text/html"
      headers["Content-Type"] = "text/html"
    end
  end

  def destroy
   if @group.members.size < 2
    @group.destroy
    redirect_to groups_path, notice: "團體刪除成功！", status: :see_other
   else
    redirect_to groups_path, notice: "請移交管理權！"
   end
  end

  def show
    find_events
    find_events_unexpired
  end

  def join
    if !current_user.member?(@group)
      current_user.join!(@group)
      flash[:notice] = '已成功加入團體！'
    else
      flash[:notice] = '你已經是本團體會員了！'
    end
    redirect_to groups_path
  end

  def quit
    if current_user.member?(@group)
      current_user.quit!(@group)
      flash[:notice] = '你已離開此團體！'
    else
      flash[:notice] = '你不是本團體會員！'
    end
    redirect_to groups_path
  end

  def find_events_unexpired
    @events_unexpired = @events.select { |event| event.date > 1.day.ago }
  end

  def manager

  end

  def transfer
    if @group.update(group_manager_params)
      redirect_to groups_path, notice: "已轉移管理權！"
    else
      render :manager
    end
  end

  private

  def find_group_self
    @group = current_user.groups.friendly.find(params[:id])
  end

  def find_group
    @group = Group.friendly.find(params[:id])
  end

  def find_events
    @events = Event.where(group: @group).includes(:store).order(:date)
  end

  def group_params
    params.require(:group).permit(:name, :description)
  end

  def group_manager_params
    params.require(:group).permit(:user_id)
  end
end

app/views/groups/_form.html.erb
<%= bootstrap_form_with model: group  do |form| %>
  <div class="row card-body">
    <div class="col-12">
      <%= form.text_field :name, class: 'form-control', autofocus: true, label: '團體名稱', required: true  %>
    </div>
    <div class="col-12 mt-3">
      <%= form.text_field :description, class: 'form-control', label: '描述' %>
    </div>
    <div class="my-3 d-flex justify-content-between">
      <%= form.submit class: 'btn btn-primary text-light' %>
      <%= link_to "移交管理權", manager_group_path(group), class: 'btn btn-outline-secondary' unless @group.new_record? %>
    </div>
  </div>
<% end %>

<!-- html: { class: 'needs-validation', novalidate: true } -->
<!-- required: true -->

app/views/groups/_group.html copy.erb
<div>
  <div class="d-flex justify-content-between align-items-center">
    <div class="d-flex align-items-center">
      <h2 class="my-0"><%= group.name %></h2>
    </div>
    <div>
      <% if group.editable?(current_user) %>
        <%= link_to edit_group_path(group), class: 'me-2' do %>
          <i class="bi bi-pencil-square fs-5"></i>
        <% end %>
          <%= link_to group_path(group), class: 'text-danger' , data: { turbo_method: :delete, turbo: true,
            turbo_confirm: '確認是否刪除？' } do %>
            <i class="bi bi-trash fs-5"></i>
          <% end %>
      <% end %>
      <% if group.members.size > 1 %>
        <%= link_to "離開團體", quit_group_path(group), class: 'btn btn-primary text-light', data: { turbo_method: :post, turbo: true, turbo_confirm: '真的要離開嗎？'} %>
      <% end %>
    </div>
  </div>
  <p class="fs-5 my-2"><%= group.description %></p>
</div>

<div class="row">
  <div class="col-12 col-md-6 mb-3">
    <div class="card">
      <div class="card-header d-flex justify-content-between align-items-center p-3">
        <div>
          <span class="fs-5 fw-bold">團體成員</span>
        </div>
        <div class="ms-auto">
          <span class="text-primary">
            團體管理員：<%= group.owner.email %>
          </span>
        </div>
      </div>
      <div class="card-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">email</th>
              <th scope="col">暱稱</th>
            </tr>
          </thead>
          <tbody>
            <% group.members.each do |member| %>
              <tr>
                <th scope="row"></th>
                <td><%= member.email %></td>
                <td><%= member.nickname %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-12 col-md-6">
    <div class="card mb-3">
      <div class="card-header d-flex justify-content-between align-items-center p-3">
        <div>
          <span class="fs-5 fw-bold">團體活動</span>
        </div>
        <div class="ms-auto">
          <%= link_to "建立活動", new_event_path(group: group.slug), class: 'btn btn-outline-secondary btn-sm' %>
        </div>
      </div>
      <div class="card-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">日期</th>
              <th scope="col">時段</th>
              <th scope="col">店家名稱</th>
              <th scope="col">功能</th>
            </tr>
          </thead>
          <tbody>
            <% @events_unexpired.each do |event| %>
              <tr>
                <th scope="row">
                  <%= event.date.strftime("%Y-%m-%d") %>
                </th>
                <td>
                  <%= t(event.period, :scope => "event.period") %>
                </td>
                <td>
                  <%= event.store.name %>
                </td>
                <td>
                  <i class="fa-solid fa-utensils me-2"></i>
                  <% if current_user==event.user %>
                    <%= link_to edit_event_path(event) do %>
                      <i class="bi bi-pencil-square fs-5"></i>
                    <% end %>
                    <%= link_to event_path(event), data: { turbo_method: :delete, turbo: true, turbo_confirm: '確認是否刪除？' } do %>
                      <i class="bi bi-trash fs-5"></i>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="card mb-3">
      <div class="card-body">
        <div data-controller="invite">
          <span class="fs-5 fw-bold">邀請連結</span>
          <input type="text" class="form-control w-100 my-2" name="" id="url" value="<%= new_invite_membership_url(group.token) %>" data-invite-target="url" data-invite-token="<%= group.token.invite_token %>" data-group-id="<%= group.id %>">
          <div class="d-flex justify-content-around align-items-center">
            <% if group.editable?(current_user) %>
              <button class="btn btn-primary text-light" id="regenerate-btn" data-action="click->invite#regenerate">重新生成</button>
            <% end %>
            <button class="btn btn-secondary" id="copy-url-btn" data-action="click->invite#copy">複製連結</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Toast -->
<div class="toast-container position-fixed bottom-0 end-0 p-3">
  <div id="toast-view"  class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay=3000>
    <div class="d-flex">
      <div class="toast-body">
        TEST!
      </div>
      <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>
</div>

app/views/groups/_group.html.erb
<div class="row">
  <div class="col-12 col-md-3 mb-2">
    <h2 class="my-0"><%= group.name %></h2>
    <p class="fs-6 my-2"><%= group.description %></p>

    <div class="d-flex flex-md-column justify-content-evenly">
      <% if group.editable?(current_user) %>
        <%= link_to '編輯團體資訊', edit_group_path(group), class: 'btn btn-sm btn-success mb-2' %>
          <%= link_to '刪除團體', group_path(group), class: 'btn btn-sm btn-danger mb-2' , data: { turbo_method: :delete, turbo: true, turbo_confirm: '確認是否刪除？' } %>
      <% end %>
      <% if group.members.size > 1 %>
        <%= link_to "離開團體", quit_group_path(group), class: 'btn btn-sm btn-primary text-light mb-2', data: { turbo_method: :post, turbo: true, turbo_confirm: '真的要離開嗎？'} %>
      <% end %>
    </div>

    <div class="card mb-3">
      <div class="card-body p-2">
        <div data-controller="invite">
          <span class="fs-5 fw-bold">邀請連結</span>
          <input type="text" class="form-control w-100 my-2" name="" id="url" value="<%= new_invite_membership_url(group.token) %>" data-invite-target="url" data-invite-token="<%= group.token.invite_token %>" data-group-id="<%= group.id %>">
          <div class="d-flex flex-md-column justify-content-evenly">
            <% if group.editable?(current_user) %>
              <button class="btn btn-sm btn-primary text-light mb-2" id="regenerate-btn" data-action="click->invite#regenerate">重新生成</button>
            <% end %>
            <button class="btn btn-sm btn-secondary mb-2" id="copy-url-btn" data-action="click->invite#copy">複製連結</button>
          </div>
        </div>
      </div>
    </div>

  </div>
  
  <div class="col-12 col-md-9 mb-2">

    <div class="card mb-3">
      <div class="card-header d-flex justify-content-between align-items-center p-3">
        <div>
          <span class="fs-5 fw-bold">團體活動</span>
        </div>
        <div class="ms-auto">
          <%= link_to "建立活動", new_event_path(group: group.slug), class: 'btn btn-success btn-sm' %>
        </div>
      </div>
      <div class="card-body">
        <% if @events_unexpired.empty?  %>
        <div class="d-flex justify-content-center align-items-center">
          <h5>目前沒有任何活動</h5>  
        </div>
        <% else %>
          <div class="list-group list-group-flush">
            <div class="list-group-item list-group-item-action list-group-item-primary fw-bold">
              <div class="d-flex justify-content-center align-items-center">
                <div class="col-5">日期</div>
                <div class="col-3">時段</div>
                <div class="col-4">店家</div>
              </div>
            </div>
            <% @events_unexpired.each do |event| %>
              <div class="list-group-item list-group-item-action">
                <%= link_to event_path(event) do %>
                  <div class="d-flex justify-content-center align-items-center">
                    <div class="col-5">
                      <%= event.date.strftime("%Y-%m-%d") %>
                    </div>
                    <div class="col-3">
                      <%= t(event.period, :scope=> "event.period") %>
                    </div>
                    <div class="col-4">
                      <%= event.store.name %>
                    </div>
                  </div>
                  <% end %>
              </div>
              <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="card mb-3">
      <div class="card-header d-flex justify-content-between align-items-center p-3">
        <div>
          <span class="fs-5 fw-bold">團體成員</span>
        </div>
        <div class="ms-auto">
          <span class="text-primary">
            團體管理員：<%= group.owner.email %>
          </span>
        </div>
      </div>
      <div class="card-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">email</th>
              <th scope="col">暱稱</th>
            </tr>
          </thead>
          <tbody>
            <% group.members.each do |member| %>
              <tr>
                <th scope="row"></th>
                <td><%= member.email %></td>
                <td><%= member.nickname %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>

<!-- Toast -->
<div class="toast-container position-fixed bottom-0 end-0 p-3">
  <div id="toast-view"  class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay=3000>
    <div class="d-flex">
      <div class="toast-body">
        TEST!
      </div>
      <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<div class="card">
  <div class="card-header d-flex">
    <div>
      <span class="fs-3">編輯團體</span>
    </div>
  </div>
  <%= render 'form', group: @group %>
</div>

app/views/groups/index.html.erb
<div class="d-flex justify-content-between align-items-start">
  <h2>已加入的團體清單</h2>
  <%= link_to "新增團體", new_group_path, class: 'btn btn-success mb-2' %>
</div>

<div class="list-group">
  <% @groups.each do |group| %>
    <%= link_to group_path(group), class: 'list-group-item list-group-item-action' do %>
      <div class="text-primary fs-5">
        <%= group.name %>  
      </div>  
      <p class="text-muted fs-6 ms-3 mt-1 mb-1">
        <%= group.description %>
      </p>
    <% end %>
  <% end %>
</div>

app/views/groups/manager.html.erb
<div class="card" data-controller="admin">
  <div class="card-header d-flex">
    <div>
      <span class="fs-3">
        <%= @group.name %>
        轉移管理權
      </span>
    </div>
  </div>
  <%= form_with model: @group, url: transfer_group_path(@group) ,data: "turbo: false" do |form| %>
    <div class="row card-body">
      <div class="col-12">
        <%= form.label :user_id, '會員email', class: 'form-label' %>
        <%= form.select :user_id, @group.members.map{ |user| [ user.email , user.id] }, {}, class: 'form-control group-user_id' , style: "width: 100%" %>
      </div>
      <div class="my-3 d-flex justify-content-between">
        <%= form.submit '轉移管理權', class: 'btn btn-primary text-light' %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/new.html.erb
<div class="card">
  <div class="card-header d-flex">
    <div>
      <span class="fs-3">新增團體</span>
    </div>
  </div>
  <%= render 'form', group: @group %>
</div>

app/views/groups/show.html.erb
<% if current_user.member?(@group) %>
  <%= render 'group', group: @group %>
<% elsif %>
  <div class="card text-center text-secondary border-secondary m-5">
    <div class="card-body">
      <h3>你還沒加入這個團體，所以無法查看內容喔！</h3>
    </div>
  </div>
<% end %>