config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :stores do
    member do
      put :sort  #stores/sort
    end
  end

  resources :groups do
    member do
      # post :join
      post :quit
      get :manager
      patch :transfer  #groups/1234567/manager
    end
    resource :invite_link, only: [ :show ]
  end
  
  resources :invites, param: :invite_token, only: [ :new ] do
    resources :memberships, only: [ :new, :create ]
  end
  
  resources :events do
  end
  
  resources :trays do
  end
  #trays/1234567/create

  # Defines the root path route ("/")
  root "home#index"
end

app/views/shared/_flash.html.erb
<div class="alert alert-warning d-flex align-items-center" role="alert">
  <i class="bi bi-exclamation-circle fs-4 me-2"></i>
  <div>
    <%= notice %><%= alert %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center border-top mt-5">
  <div class="col-md-6 text-muted">
    <i class="fa-regular fa-copyright"></i>
    2022 tskysora
  </div>
  <!-- <div class=" d-flex col-md-4 justify-content-center align-items-center">
    <i class="fa-solid fa-utensils fs-4"></i>
  </div> -->
  <ul class="nav col-md-6 list-unstyled justify-content-end">
    <li class="nav-item">
      <a href="#" class="nav-link text-muted">首頁</a>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link text-muted">功能</a>
    </li>
    <li class="nav-item">
      <a href="#" class="nav-link text-muted">關於</a>
    </li>
  </ul>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-primary" data-turbo="false">
  <div class="container-fluid">
    <%= link_to(root_path, class: 'navbar-brand') do %>
      <i class="fa-solid fa-utensils me-2"></i>吃些什麼
    <% end %>

    <!-- Sidebar -->
    <div class="d-block d-md-none">
      <button class="navbar-toggler shadow-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <%= link_to(root_path, class: 'fs-5 text-black text-decoration-none') do %>
            <i class="fa-solid fa-utensils me-2"></i>吃些什麼
          <% end %>
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <%= link_to "首頁", root_path, class: 'nav-link ps-4' %>
          <% if user_signed_in? %>
            <!-- <a class="nav-link ps-4" href="#">跟團</a> -->
            <%= link_to "團體", groups_path, class: 'nav-link ps-4' %>
            <%= link_to "活動", events_path, class: 'nav-link ps-4' %>
            <!-- <div id="sidebar-mobile-collapse-btn" class="nav-link ps-1 cursor-pointer">
              <i class="bi bi-chevron-down me-1" id="sidebar-mobile-icon"></i>
              <span>管理</span>
            </div>
            <div id="sidebar-mobile-collapse" class="ms-2">
              <%= link_to "我的店家清單", stores_path, class: 'nav-link' %>
              <a class="nav-link" href="#">餐點管理</a>
            </div> -->
            <%= link_to "我的店家清單", stores_path, class: 'nav-link ps-4' %>
          <% end %>
        </div>
        <div class="offcanvas-footer">
          <!-- <hr> -->
          <% if user_signed_in? %>
            <div class="btn-group dropup py-2 w-100 border-top">
              <button type="button" class="btn dropdown-toggle shadow-none text-start" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.email %>
              </button>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to "個人資料", edit_user_registration_path, class: 'dropdown-item' %>
                </li>
                <li><hr class="dropdown-divider"></li>
                <%= link_to "登出", destroy_user_session_path, data: { turbo_method: :delete, turbo: true }, class: 'dropdown-item' %>
              </ul>
            </div>
          <% else %>
            <div class="d-flex justify-content-evenly align-items-center border-top">
                <%= link_to "註冊", new_user_registration_path, class: 'btn my-2 w-50 border-end' %>
                <%= link_to "登入", new_user_session_path, class: 'btn my-2 w-50' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    
    <!-- Extend Navbar -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= link_to "首頁", root_path, class: 'nav-link active' %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "團體", groups_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "活動", events_path, class: 'nav-link' %>
          </li>
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              管理
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "我的店家清單", stores_path, class: 'dropdown-item' %></li>
              <li><a class="dropdown-item" href="#">餐點管理</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li> -->
          <li class="nav-item">
            <%= link_to "我的店家清單", stores_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <% if user_signed_in? %>
          <div class="dropdown">
            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownUserButton" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownUserButton">
              <li>
                <%= link_to "個人資料", edit_user_registration_path, class: 'btn btn-outline-info dropdown-item me-1' %>
              </li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
              <li><hr class="dropdown-divider"></li>
              <%= link_to "登出", destroy_user_session_path, data: { turbo_method: :delete, turbo: true }, class: 'dropdown-item' %>
            </ul>
          </div>
        <% else %>
          <%= link_to "註冊", new_user_registration_path, class: 'btn btn-outline-success me- 1' %>
          <%= link_to "登入", new_user_session_path, class: 'btn btn-outline-light me-1' %>
        <% end %>
      </form>
    </div>
  </div>
</nav>