config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :stores do
    member do
      put :sort  #stores/sort
    end
  end

  resources :groups do
    member do
      # post :join
      post :quit
      get :manager
      patch :transfer  #groups/1234567/manager
    end
    resource :invite_link, only: [ :show ]
  end
  
  resources :invites, param: :invite_token, only: [ :new ] do
    resources :memberships, only: [ :new, :create ]
  end
  
  resources :events do
  end
  
  resources :trays do
  end
  #trays/1234567/create

  # Defines the root path route ("/")
  root "home#index"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :store
  belongs_to :group
  belongs_to :user
  has_one :tray, dependent: :destroy

  validates :date, :period, presence: true

  PERIOD = ["breakfast", "lunch", "dinner"]
  validates_inclusion_of :period, :in => PERIOD

  extend FriendlyId
  friendly_id :code_generator, use: :slugged

  def expired?(date)
    # date < Time.zone.now
    date < 1.day.ago
  end

  def unexpired?(date)
    # date < Time.zone.now
    date > 1.day.ago
  end

  private
  def code_generator
    "#{period} - #{SecureRandom.hex[0,20]}"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_group, only: [:new, :create]
  before_action :find_event, only: [:edit, :update, :show, :destroy]
  
  def index
    find_events_expired
    find_events_unexpired
  end

  def new
    @event = current_user.events.new
  end

  def create
    @event = current_user.events.new(event_params)
    
    if @event.save!
      redirect_to events_path, notice: '新增活動成功！'
    else
      render :new, status: :unprocessable_entity, content_type: "text/html"
      headers["Content-Type"] = "text/html"
    end
  end

  def edit
    
  end

  def update
    if @event.update(event_params)
      redirect_to events_path, notice: "活動更新成功！"
    else
      render :edit, status: :unprocessable_entity, content_type: "text/html"
      headers["Content-Type"] = "text/html"
    end
  end

  def show
    find_tray
    if @tray
      
    else
      @tray = Tray.new
      @tray.tray_items.build
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: "活動刪除成功！", status: :see_other
  end

  def find_events_expired
    @events = Event.where(group: current_user.participated_groups).includes(:group, :store, :user).order(date: :desc)
    @events_expired = @events.select { |event| event.date < 1.day.ago }
  end

  def find_events_unexpired
    @events = Event.where(group: current_user.participated_groups).includes(:group, :store, :user).order(date: :asc)
    @events_unexpired = @events.select { |event| event.date > 1.day.ago }
  end

  private
  
  def find_group
    @group = Group.find_by(slug: params[:group])
  end

  def find_event
    @event = Event.friendly.find(params[:id])
  end
  
  def find_tray
    @event = Event.friendly.find(params[:id])
    @tray = Tray.find_by(event_id: @event.id)
  end

  def event_params
    params.require(:event).permit(:date, :store_id, :period, :group_id)
  end

end

app/views/events/_event_list.html.erb
<!-- <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">日期</th>
      <th scope="col">時段</th>
      <th scope="col">店家</th>
      <th scope="col">發起的團體</th>
      <th scope="col">功能</th>
    </tr>
  </thead>
  <tbody>
    <% events.each do |event| %>
      <tr>
        <th scope="row">
          <%= event.date.strftime("%Y-%m-%d") %>
        </th>
        <td>
          <%= t(event.period, :scope=> "event.period") %>
        </td>
        <td>
          <%= event.store.name %>
        </td>
        <td>
          <%= event.group.name %>
        </td>
        <td>
          <i class="fa-solid fa-utensils me-2"></i>
          <% if current_user==event.user %>
            <%= link_to edit_event_path(event) do %>
              <i class="bi bi-pencil-square fs-5"></i>
            <% end %>
            <%= link_to event_path(event), data: { turbo_method: :delete, turbo: true, turbo_confirm: '確認是否刪除？' } do %>
              <i class="bi bi-trash fs-5"></i>
            <% end %>
          <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table> -->

<div class="list-group mt-3">
  <div class="list-group-item list-group-item-action list-group-item-primary fw-bold">
    <div class="d-flex justify-content-center align-items-center">
      <div class="col-4">日期</div>
      <div class="col-2">時段</div>
      <div class="col-3">店家</div>
      <div class="col-3">發起的團體</div>
    </div>
  </div>
  <% events.each do |event| %>
    <div class="list-group-item list-group-item-action">
      <%= link_to event_path(event) do %>
        <div class="d-flex justify-content-center align-items-center">
          <div class="col-4">
            <%= event.date.strftime("%Y-%m-%d") %>
          </div>
          <div class="col-2">
            <%= t(event.period, :scope=> "event.period") %>
          </div>
          <div class="col-3">
            <%= event.store.name %>
          </div>
          <div class="col-3">
            <%= event.group.name %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/events/_form.html.erb
<%= bootstrap_form_with model: event, data: "turbo: false" do |form| %>
  <div class="row card-body d-flex justify-content-between align-items-center">
    <div class="col-12 mb-2">
      <%= form.text_field :date, class: 'form-control datepicker', placeholder: '挑選日期...', label: '日期', required: true %>
    </div>
    <div class="col-12 mb-2">
      <%= form.select :store_id, current_user.stores.available.map{ |store| [ "#{store.name} #{store.branch}", store.id] }, { label: '店家名稱' }, { class: 'event-store_id' } %>
    </div>
    <div class="col-12 mb-2">
      <%= form.form_group :period, label: { text: '用餐時段'} do %>
        <% Event::PERIOD.each do |period| %>
          <%= form.radio_button :period, period, label: t(period, :scope => "event.period"), inline: true, required: true %>
        <% end %>
      <% end %>
    </div>
    <div class="col-12">
      <% if @group %>
        <%= form.hidden_field :group_id, value: @group.id %>
      <% else %>
        <%= form.hidden_field :group_id, value: event.group_id %>
      <% end %>
    </div>
    
    <div class="">
      <%= form.submit class: 'btn btn-primary text-light' %>
    </div>
  </div>
<% end %>

app/views/events/_tray_form.html.erb
<div class="row nested-tray-fields my-2" data-new-record="<%= form.object.new_record? %>" >
  <div class="col-5">
    <%= form.collection_select :meal_id, @event.store.meals, :id, :name, { prompt: '請選擇餐點...', hide_label: true}, { class: 'form-select', required: true } %>
  </div>
  <div class="col-2">
    <%= form.number_field :quantity, class: 'form-control', placeholder: '數量', required: true, hide_label: true %>
  </div>
  <div class="col-4">
    <%= form.text_field :note, class: 'form-control', placeholder: '備註', hide_label: true %>
  </div>
  <div class="col-1 align-items-center d-flex">
    <%= link_to '#' , data: {action: 'tray-items#remove_tray' } do %>
      <i class="bi bi-trash fs-5"></i>
    <% end %>
  </div>
  <%= form.hidden_field :_destroy %>
</div>

app/views/events/edit.html.erb
<div class="card">
  <div class="card-header d-flex">
    <div>
      <span class="fs-3">編輯活動</span>
    </div>
  </div>
  <%= render 'form', event: @event %>
</div>

app/views/events/index.html.erb
<h2>所有活動清單</h2>

<!-- Nav tabs -->
<ul class="nav nav-tabs" id="eventTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="unexpired-tab" data-bs-toggle="tab" data-bs-target="#unexpired" type="button"
      role="tab" aria-controls="unexpired" aria-selected="true">未到期的活動</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="expired-tab" data-bs-toggle="tab" data-bs-target="#expired" type="button" role="tab"
      aria-controls="expired" aria-selected="false">過期的活動</button>
  </li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="unexpired" role="tabpanel" aria-labelledby="unexpired-tab" tabindex="0">
    <%= render 'event_list' , events: @events_unexpired %>
  </div>
  <div class="tab-pane" id="expired" role="tabpanel" aria-labelledby="expired-tab" tabindex="0">
    <%= render 'event_list' , events: @events_expired %>
  </div>
</div>

app/views/events/new.html.erb
<div class="card">
  <div class="card-header d-flex">
    <div>
      <span class="fs-3">新增活動</span>
    </div>
  </div>
  <%= render 'form', event: @event %>
</div>

app/views/events/show.html.erb
<div class="row">
  <div class="col-12 col-md-2 mb-2">
    <div class="row">
      <div class="col-7 col-md-12">
        <p class="m-0"><%= @event.date.strftime("%Y") %></p>
        <h3 class="m-0"><%= @event.date.strftime("%m-%d") %></h3>
        <p class="fs-5 my-2"><%= t(@event.period, :scope=> "event.period") %></p>
        <%= link_to @event.group.name , group_path(@event.group), class: 'fs-5' %>
      </div>
      <div class="col-5 col-md-12">
        <% if current_user==@event.user %>
          <div class="d-flex flex-column mt-4">
            <%= link_to '編輯活動資訊', edit_event_path(@event), class: 'btn btn-sm btn-success mb-2' %>
            <%= link_to '刪除活動', event_path(@event), class: 'btn btn-sm btn-danger mb-2' , data: { turbo_method: :delete, turbo: true, turbo_confirm: '確認是否刪除？' } %>
            <%= link_to 'new tray', new_tray_path(@tray), class: 'btn btn-sm btn-success mb-2' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-12 col-md-10 mb-2">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <div>
          <span class="fs-4">
            <%= @event.store.name %>
            <%= @event.store.branch %>
          </span>
          <span>的菜單</span>
        </div>
        <div>
          <button class="btn btn-sm btn-primary text-light" type="button" data-bs-toggle="collapse"
            data-bs-target=".collapse-meals">
            看看別人點了什麼
          </button>
        </div>
      </div>
      <div class="row card-body d-flex justify-content-between align-items-center">
        <div class="col-12">
          <div class="">
            <div class="row py-2 border-bottom item border-2">
              <div class="col-2"></div>
              <div class="col-4">品項</div>
              <div class="col-2">價格</div>
              <div class="col-4">描述</div>
            </div>
            <% @event.store.meals.each do |meal| %>
              <div class="row py-2 border-bottom item">
                <div class="col-2">
                  <%= link_to "加入餐盤", "#", class: 'btn-sm btn-secondary' %>
                </div>
                <div class="col-4">
                  <%= meal.name %>
                </div>
                <div class="col-2">
                  <%= meal.price %>
                </div>
                <div class="col-4">
                  <%= meal.description %>
                </div>
                <div class="col-12 collapse collapse-meals" id="collapseMeals">
                  <div class="">
                    Some placeholder content for the collapse component. This panel is hidden by default but revealed when the user
                    activates the relevant trigger.
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="card mt-3">
      <div class="card-header d-flex">
        <div>
          <span class="fs-4">
            我的餐盤
          </span>
        </div>
      </div>
      <div class="row card-body d-flex justify-content-between align-items-center">
        <div class="col-12 mb-3">
          <div class="row">
            <div class="col-5">
              品項
            </div>
            <div class="col-2">
              數量
            </div>
            <div class="col-4">
              備註
            </div>
            <%= bootstrap_form_with model: @tray do |form| %>
              <div>
                <%= form.hidden_field :event_id, value: @event.id %>
              </div>
              <div data-controller="tray-items">
                <template data-tray-items-target="templateTray">
                  <%= form.fields_for :tray_items, TrayItem.new, child_index: 'NEW_RECORD' do |tray| %>
                    <%= render 'tray_form' , form: tray %>
                  <% end %>
                </template>
                <%= form.fields_for :tray_items do |tray_form| %>
                  <%= render 'tray_form' , form: tray_form %>
                <% end %>
                <div data-tray-items-target="addTrayBtn">
                  <%= link_to "新增品項", '#', class: 'btn btn-sm btn-secondary', data: {action: 'tray-items#add_tray_item'} %>
                </div>
              </div>
              <div class="my-3 d-flex justify-content-between">
                <%= form.submit class: 'btn btn-primary text-light' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>